models/Documentation.php
<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;
use yii\web\UploadedFile;

class Documentation extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc 
     */ 
    public $other_file;
    public static function tableName()
    {
        return 'documentation';
    }

    /**
     * @inheritdoc
     */
    public function rules() 
    {
        return [
            [['date'], 'safe'],
            [['working'], 'string'],
            [['stage_id', 'users_id','client_id','documents_type_id'], 'integer'],
            [['number', 'ownership', 'file'], 'string', 'max' => 255],
            [['stage_id'], 'exist', 'skipOnError' => true, 'targetClass' => StagesDocument::className(), 'targetAttribute' => ['stage_id' => 'id']],
            [['users_id'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['users_id' => 'id']],
            [['client_id'], 'exist', 'skipOnError' => true, 'targetClass' => Client::className(), 'targetAttribute' => ['client_id' => 'id']],
            [['other_file'], 'file'],
            [['users_id','stage_id','client_id'], 'required'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date' => 'Дата',
            'number' => 'Номер',
            'ownership' => 'Принадлежность',
            'working' => 'Рабочие названия ',
            'stage_id' => 'Этап',
            'other_file' => 'Файл',
            'users_id' => 'Кто',
            'file'=>'Файл',
            'client_id' => 'Клиент',
            'documents_type_id'=> 'Тип документа',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function beforeSave($insert)
    {  
        if($this->date != null) $this->date = \Yii::$app->formatter->asDate($this->date, 'php:Y-m-d');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function getStage()
    {
        return $this->hasOne(StagesDocument::className(), ['id' => 'stage_id']);
    }
    public function getDocumentstype()
    {
        return $this->hasOne(Documentstype::className(), ['id' => 'documents_type_id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasOne(Users::className(), ['id' => 'users_id']);
    }
    public function getClient()
    {
        return $this->hasOne(Client::className(), ['id' => 'client_id']);
    }
    public function getClients()
    {
        return ArrayHelper::map(Client::find()->all(), 'id', 'working_title');
    }
    public function getStagesList()
    {
        return ArrayHelper::map(StagesDocument::find()->all(), 'id', 'name');
    }
    public function getDocumentstypes()
    {
        return ArrayHelper::map(Documentstype::find()->all(), 'id', 'name');
    }
}

controllers/DocumentationController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Documentation;
use app\models\DocumentationSearch;
use yii\web\UploadedFile;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
  
/**
 * DocumentationController implements the CRUD actions for Documentation model.
 */
class DocumentationController extends Controller
{
    /**
     * @inheritdoc
     */ 
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                   [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Documentation models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $searchModel = new DocumentationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single Documentation model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "Документы ",
                    'size' => 'large',
                    'content'=>$this->renderAjax('view', [
                        'model' => $this->findModel($id),
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn otmena pull-left','data-dismiss'=>"modal"]).
                            Html::a('Изменить',['update','id'=>$id],['class'=>'btn btn save','role'=>'modal-remote'])
                ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }
    public function upload()
    {

        if ($this->validate()) {
            $this->file->saveAs('uploads/' . $this->file->baseName . '.' . $this->imageFile->extension);
            return true;
        } else {
            return false;
        }
    }
    /**
     * Creates a new Documentation model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionAdd($client_id)
    {
        $request = Yii::$app->request;
        $model = new Documentation(); 
        $model->client_id = $client_id;  
            
        Yii::$app->response->format = Response::FORMAT_JSON;
       
        if($model->load($request->post()) && $model->save()){

            $model->other_file = UploadedFile::getInstance($model, 'other_file');

            $fileName = $model->other_file->baseName . '.' . $model->other_file->extension;
            if ($model->other_file && $model->validate()) {
                $model->other_file->saveAs('uploads/' . $fileName);
                $model->file =  $fileName;
                $model->save();
            }

            return [
                'forceReload'=>'#documentation-datatable-pjax',
                'size' => 'normal',
                'title'=> "Документы",
                'content'=>'<span class="text-success">Успешно добавлено</span>',
                'footer'=> Html::button('Ок',['class'=>'btn btn otmena pull-left','data-dismiss'=>"modal"]).
                        Html::a('Создать ещё',['/documentation/add', 'client_id' => $client_id],['class'=>'btn btn save','role'=>'modal-remote'])        
            ];         
        }else{           
            return [ 
                'title'=> "Добавить. Документ",
                'size' => 'large',
                'content'=>$this->renderAjax('/documentation/add', [
                    'model' => $model,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn otmena pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn save','type'=>"submit"])        
            ];         
        }     
    }

    //Загрузить файл на сервер
    public function actionSendDocumentFile($file)
    {
        return \Yii::$app->response->sendFile('uploads/' . $file);
    }
    
    /**
     * Updates an existing Documentation model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdateDocumentation($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);       

        Yii::$app->response->format = Response::FORMAT_JSON;
        if($model->load($request->post()) && $model->save()){
            $model->other_file = UploadedFile::getInstance($model, 'other_file');

            $fileName = $model->other_file->baseName . '.' . $model->other_file->extension;
            if ($model->other_file && $model->validate()) {
                $model->other_file->saveAs('uploads/' . $fileName);
                $model->file =  $fileName;
                $model->save();
            }
            return ['forceClose'=>true,'forceReload'=>'#documentation-datatable-pjax'];
        }else{
             return [
                'title'=> "Изменить",
                'size' => 'large',
                'content'=>$this->renderAjax('/documentation/add', [
                    'model' => $model,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn otmena pull-left','data-dismiss'=>"modal"]).
                            Html::button('Сохранить',['class'=>'btn btn save','type'=>"submit"])
            ];        
        }
    }
    /**
     * Delete an existing Documentation model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDeleteDocumentation($id)
    {
        $request = Yii::$app->request;
        $model = Documentation::findOne($id);
        $imageName = $model->file;
        Yii::$app->db->createCommand()->delete('documentation', ['id' => $id])->execute();
        unlink(getcwd().'/uploads/'.$imageName);

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#documentation-datatable-pjax'];
        }
    }
    /**
     * Creates a new Documentation model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Documentation();  

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Создать",
                    'size' => 'large',
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn otmena pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn save','type'=>"submit"])
        
                ];         
            }else if($model->load($request->post()) && $model->save()){

                    $model->other_file = UploadedFile::getInstance($model, 'other_file');

                    $fileName = $model->other_file->baseName . '.' . $model->other_file->extension;
                    if ($model->other_file && $model->validate()) {
                        $model->other_file->saveAs('uploads/' . $fileName);
                        $model->file =  $fileName;
                        $model->save();
                    }
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Создать",
                    'size' => 'large',
                    'content'=>'<span class="text-success">Создания документы успешно завершено</span>',
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn otmena pull-left','data-dismiss'=>"modal"]).
                            Html::a('Создать ещё',['create'],['class'=>'btn btn save','role'=>'modal-remote'])
        
                ];         
            }else{           
                return [
                    'title'=> "Создать",
                    'size' => 'large',
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn otmena pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn save','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {

views/documentation/_columns.php
<?php
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use app\models\Client;
use app\models\StagesDocument;
use app\models\Documentstype;
use app\models\Users;
use yii\helpers\Html;
return [
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'working',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'client_id',
        'filter' => ArrayHelper::map(Client::find()->all(),'id','working_title'),
        'content' => function ($data) {
            return $data->client->working_title;
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'stage_id',
        'filter' => ArrayHelper::map(StagesDocument::find()->all(),'id','name'),
        'content' => function ($data) {
            return $data->stage->name;
        },
    ],
     [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'documents_type_id',
        'filter' => ArrayHelper::map(Documentstype::find()->all(),'id','name'),
        'content' => function ($data) {
            return $data->documentstype->name;
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'users_id',
        'filter' => ArrayHelper::map(Users::find()->all(),'id','fio'),
        'content' => function ($data) {
            return $data->users->fio;
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'file',
        'content' => function ($data) {
            return Html::a($data->file, ['/documentation/send-document-file', 'file' => $data->file],['title'=> 'Скачать', 'data-pjax' => 0]);
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'date',
    ],

    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'number',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'ownership',
    ],
   
    
   [
        'class' => 'kartik\grid\ActionColumn',
        'template' => '{view}{update}{delete}',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['role'=>'modal-remote','data-pjax'=>0,'title'=>'','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'', 
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Подтвердите действие',
                          'data-confirm-message'=>'Вы уверены что хотите удалить данного документы?'], 
    ],

];   

views/documentation/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
/* @var $this yii\web\View */
/* @var $model app\models\Documentation */
/* @var $form yii\widgets\ActiveForm */
?>
<head>
    <link href="/theme/assets/css/new.css" rel="stylesheet" />
</head>
<body > 
<div class="documentation-form"> 

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">

        <img style="width: 100%;margin-top: -60px;" src="/theme/assets/img/chiziq95.png" alt="">
        <div class="col-md-2 label1">
            <?=$model->getAttributeLabel('working')?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'working')->textInput(['maxlength' => true])->label(""); ?>
        </div>
        <div class="col-md-2 label1">
            <?=$model->getAttributeLabel('client_id')?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'client_id')->label()->widget(\kartik\select2\Select2::classname(), [
                'data' => $model->getClients(),
                'id' => 'type',
                'options' => ['placeholder' => 'Выберите'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]) ?>
        </div>
    </div>
    <div class="row"> 
        <div class="col-md-2 label1" style="margin-top: 10px">
            <?=$model->getAttributeLabel('date')?>
        </div>
        <div class="col-md-4" style="margin-top: -10px">
            <?= $form->field($model, 'date')->widget(DatePicker::classname(), [
                'options' => ['placeholder' => 'Выберите дату', 'value' => date('d.m.Y')],
                'removeButton' => false,
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'dd.mm.yyyy',
                ]
            ])->label(""); 
            ?>
        </div>
        <div class="col-md-2 label1" style="margin-top: 10px">
            <?=$model->getAttributeLabel('documents_type_id')?>
        </div>
        <div class="col-md-4" style="margin-top: -10px">
           <?= $form->field($model, 'documents_type_id')->dropDownList($model->getDocumentstypes(), ['prompt' => 'Выберите', 'id' => 'type'])->label(""); ?>
        </div> 
    </div>
    <div class="row">
        <div class="col-md-2 label1" style="margin-top: 10px">
            <?=$model->getAttributeLabel('ownership')?>
        </div>
        <div class="col-md-4" style="margin-top: -10px">
            <?= $form->field($model, 'ownership')->textInput(['maxlength' => true])->label(""); ?>            
        </div>
        <div class="col-md-2 label1" style="margin-top: 10px">
            <?=$model->getAttributeLabel('number')?>
        </div>
        <div class="col-md-4" style="margin-top: -10px">
           <?= $form->field($model, 'number')->textInput(['maxlength' => true])->label(""); ?>
        </div>
        <div class="col-md-2 label2" style="margin-top: 25px">
            <?=$model->getAttributeLabel('other_file')?>
        </div>
         <div class="col-md-4" style="margin-top: 10px">
            <?= $form->field($model, 'other_file')->fileInput()->label(""); ?>            
        </div>
        <div class="col-md-2 label1" style="margin-top: 10px">
            <?=$model->getAttributeLabel('stage_id')?>
        </div>
         <div class="col-md-4" style="margin-top: -10px">
            <?= $form->field($model, 'stage_id')->dropDownList($model->getStagesList(), ['prompt' => 'Выберите', 'id' => 'type'])->label(""); ?>
        </div>
    </div>

    <div style="display: none;">
        <?= $form->field($model, 'users_id')->textInput(['value' => \Yii::$app->user->identity->id]) ?>    
    </div>
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>
</body>

views/documentation/add.php
<?php

use yii\helpers\Html;

?>
<div class="documentation-create">
    <?= $this->render('add_form', [
        'model' => $model,
    ]) ?>
</div>

views/documentation/add_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
 
?>

<div class="call-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
    <div class="row">
        <img style="width: 100%;margin-top: -60px;" src="/theme/assets/img/chiziq95.png" alt="">
        <div class="col-md-2 label1">
            <?=$model->getAttributeLabel('working')?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'working')->textInput(['maxlength' => true])->label(""); ?>
        </div>
        <div class="col-md-1 label1" >
            <?=$model->getAttributeLabel('date')?>
        </div>
        <div class="col-md-5">
            <?= $form->field($model, 'date')->widget(DatePicker::classname(), [
                'options' => ['placeholder' => 'Выберите дату', 'value' => date('d.m.Y')],
                'removeButton' => false,
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'dd.mm.yyyy',
                ]
            ])->label(""); 
            ?>
        </div> 
    </div>

    <div class="row">
        <div class="col-md-2 label1" >
            <?=$model->getAttributeLabel('ownership')?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'ownership')->textInput(['maxlength' => true])->label(""); ?>            
        </div>
        <div class="col-md-1 label1" >
            <?=$model->getAttributeLabel('number')?>
        </div>
        <div class="col-md-5">
           <?= $form->field($model, 'number')->textInput(['maxlength' => true])->label(""); ?>
        </div>
        <div class="col-md-2 label1" >
            <?=$model->getAttributeLabel('documents_type_id')?>
        </div>
        <div class="col-md-4">
           <?= $form->field($model, 'documents_type_id')->dropDownList($model->getDocumentstypes(), ['prompt' => 'Выберите', 'id' => 'type'])->label(""); ?>
        </div>
        <div class="col-md-1 label1" >
            <?=$model->getAttributeLabel('stage_id')?>
        </div>
         <div class="col-md-5">
            <?= $form->field($model, 'stage_id')->dropDownList($model->getStagesList(), ['prompt' => 'Выберите', 'id' => 'type'])->label(""); ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-1 label2" >
            <?=$model->getAttributeLabel('other_file')?>
        </div>
         <div class="col-md-4" >
            <?= $form->field($model, 'other_file')->fileInput()->label(""); ?>            
        </div>
    </div>

    <div style="display: none;">
        <?= $form->field($model, 'users_id')->textInput(['value' => \Yii::$app->user->identity->id]) ?>    
        <?= $form->field($model, 'client_id')->textInput() ?>     
    </div>

    <?php ActiveForm::end(); ?>
    
</div>

views/documentation/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Documentation */

?>
<div class="documentation-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/documentation/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;



$this->title = "Документы";
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<head>
    <link href="/theme/assets/css/new.css" rel="stylesheet" />
</head>
<div class="panel panel-inverse documentation-index leftindex">
    <div class="panel-heading" style="background: #28292b">
        <h4 class="panel-title rabsize3 left1">Документы</h4>
    </div>
    <div class="panel-body">
        <div id="ajaxCrudDatatable">
            <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'pjax'=>true,
            'columns' => require(__DIR__.'/_columns.php'),
            'panelBeforeTemplate' =>    Html::a('Добавить <i class="fa fa"></i>', ['create'],
                    ['role'=>'modal-remote','title'=> 'Добавить','style'=>'color: #ffffff;background:#74b916;margin-left: 25px','class'=>'btn btn']).'&nbsp;'.
                Html::a('<i class="fa fa-repeat"></i>', [''],
                    ['data-pjax'=>1, 'style'=>'color: #ffffff;background:#74b916;margin-left: 12px','class'=>'btn btn', 'title'=>'Обновить']),
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'panel' => [
            'headingOptions' => ['style' => 'display: none;'],
            'after'=>'',
            ]
            ])?>
        </div>
    </div>
</div>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "options" => [
        "tabindex" => -1,
    ],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/documentation/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Documentation */
?>
<div class="documentation-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/documentation/view.php
<?php

use yii\widgets\DetailView;
use yii\helpers\ArrayHelper;
use app\models\Client;
use yii\helpers\Html;
/* @var $this yii\web\View */
/* @var $model app\models\Documentation */
?>
<div class="documentation-view">
 
    <?= DetailView::widget([ 
        'model' => $model,
        'attributes' => [
            'id',
             [
            'attribute'=>'working',
            'format'=>'ntext',   
            'contentOptions' => [
                'style'=>'max-width:150px; min-height:100px; overflow: auto; word-wrap: break-word;'
            ],
            ],
            [
                'attribute' => 'users_id',
                'value' => function ($data) {
                   return $data->users->fio;
                },
            ],
            [
                'attribute' => 'client_id',
                'value' => function ($data) {
                   return $data->client->working_title;
                },
            ],
            [
                    'attribute' => 'date',
                    'value' => function ($data) {
                     if($data->date != null )  return \Yii::$app->formatter->asDate($data->date, 'php:d.m.Y');
                    },
            ],
            'number',
            'ownership',
            'file',
            [
                'attribute' => 'stage_id',
                'value' => function ($data) {
                   return $data->stage->name;
                },
            ],
            
        ],
    ]) ?>

</div>