models/Tasks.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;
/** 
 * This is the model class for table "tasks".
 *
 * @property int $id
 * @property string $date
 * @property string $time
 * @property int $who_users_id
 * @property int $to_users_id
 * @property string $title
 * @property string $description
 * @property double $terms
 * @property int $status
 * @property string $attachment
 * @property int $client_id
 *
 * @property Client $client
 * @property Users $toUsers
 * @property Users $whoUsers
 */
class Tasks extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $other_file;
    public static function tableName()
    {
        return 'tasks';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date', 'time', 'terms'], 'safe'],
            [['who_users_id', 'to_users_id', 'status', 'client_id'], 'integer'],
            [['description'], 'string'],
            [['title', 'attachment'], 'string', 'max' => 255],
            [['client_id'], 'exist', 'skipOnError' => true, 'targetClass' => Client::className(), 'targetAttribute' => ['client_id' => 'id']],
            [['to_users_id'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['to_users_id' => 'id']],
            [['who_users_id'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['who_users_id' => 'id']],
            [['other_file'], 'file'],
            [['status','who_users_id','to_users_id','terms','title'], 'required'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date' => 'Дата',
            'time' => 'Время',
            'who_users_id' => 'От кого',
            'to_users_id' => 'Кому',
            'title' => 'Название',
            'description' => 'Описание',
            'terms' => 'Сроки',
            'status' => 'Статус',
            'attachment'=>'Файл',
            'other_file' => 'Файл',
            'client_id' => 'Клиент',
        ];
    }

    public function beforeSave($insert)
    {  
        if ($this->isNewRecord)
        {
            $this->date = date('Y-m-d');
            $this->time = date('H:i:s');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient()
    {
        return $this->hasOne(Client::className(), ['id' => 'client_id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWhoUsers()
    {
        return $this->hasOne(Users::className(), ['id' => 'who_users_id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getToUsers()
    {
        return $this->hasOne(Users::className(), ['id' => 'to_users_id']);
    }

    public function getClients()
    {
        return ArrayHelper::map(Client::find()->all(), 'id', 'working_title');
    }
    public function getUsers()
    {
        return ArrayHelper::map(Users::find()->all(), 'id', 'fio');
    }
    public function getStatus()
    {
        return ArrayHelper::map([
            ['id' => '1', 'title' => 'Выполнено',],
            ['id' => '2', 'title' => 'На проверке',],
            ['id' => '3', 'title' => 'Есть уточнение',],
            ['id' => '4', 'title' => 'Новая',],
        ],
        'id', 'title');
    }
    public function getStatusName()
    {
        if($this->status == 1) return 'Выполнено';
        if($this->status == 2) return 'На проверке';
        if($this->status == 3) return 'Есть уточнение';
        if($this->status == 4) return 'Новая';
    }
}

controllers/TasksController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Tasks; 
use app\models\TasksSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response; 
use yii\helpers\Html; 
use yii\web\UploadedFile;
use app\models\Notification;
/**
 * TasksController implements the CRUD actions for Tasks model.
 */ 
class TasksController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                   [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /** 
     * Lists all Tasks models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $searchModel = new TasksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'status' => 0,
        ]);
    }

    public function actionArchive()
    {    
        $searchModel = new TasksSearch();
        $dataProvider = $searchModel->searchArchive(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'status' => 1,
        ]);
    }

    public function actionChat()
    {    
        return $this->render('chat', [
        ]);
    }


    /**
     * Displays a single Tasks model.
     * @param integer $id 
     * @return mixed
     */
    public function actionView($id)
    {   
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> $this->findModel($id)->title,
                    'content'=>$this->renderAjax('view', [
                        'model' => $this->findModel($id),
                    ]),
                ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new Tasks model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionAdd($client_id)
    {
        $request = Yii::$app->request;
        $model = new Tasks(); 
        $model->client_id = $client_id;
        if(Yii::$app->user->identity->type == 2) $model->who_users_id = Yii::$app->user->identity->id; 
            
        Yii::$app->response->format = Response::FORMAT_JSON;
        if($model->load($request->post()) && $model->save()){
            
            $model->other_file = UploadedFile::getInstance($model, 'other_file');

            $fileName = $model->other_file->baseName . '.' . $model->other_file->extension;
            if ($model->other_file && $model->validate()) {
                $model->other_file->saveAs('uploads/' . $fileName);
                $model->attachment =  $fileName;
                $model->save();
            }
            
            Notification::setNotification('tasks', $model->id, $model->to_users_id, $model->title);
            
            return [
                'forceReload'=>'#tasks-datatable-pjax',
                'size' => 'large',
                'title'=> "Задачи",
                'content'=>'<span class="text-success">Успешно добавлено</span>',
                'footer'=> Html::button('Ок',['class'=>'btn btn otmena pull-left','data-dismiss'=>"modal"]).
                        Html::a('Создать ещё',['/tasks/add', 'client_id' => $client_id],['class'=>'btn btn save','role'=>'modal-remote'])        
            ];         
        }else{           
            return [ 
                'title'=> "Добавить. Задачи",
                'size' => 'large',
                'content'=>$this->renderAjax('/tasks/add', [
                    'model' => $model,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn otmena pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn save','type'=>"submit"])        
            ];         
        }     
    }
    /**
     * Creates a new Tasks model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionAddrab($client_id)
    {
        $request = Yii::$app->request;
        $model = new Tasks(); 
        $model->client_id = $client_id;
        if(Yii::$app->user->identity->type == 2) $model->who_users_id = Yii::$app->user->identity->id; 
            
        Yii::$app->response->format = Response::FORMAT_JSON;
        if($model->load($request->post()) && $model->save()){
            
            $model->other_file = UploadedFile::getInstance($model, 'other_file');

            $fileName = $model->other_file->baseName . '.' . $model->other_file->extension;
            if ($model->other_file && $model->validate()) {
                $model->other_file->saveAs('uploads/' . $fileName);
                $model->attachment =  $fileName;
                $model->save();
            }
            
            Notification::setNotification('tasks', $model->id, $model->to_users_id, $model->title);
            
            return [
                'forceReload'=>'#tasks-datatable-pjax',
                'size' => 'large',
                'title'=> "Задачи",
                'content'=>'<span class="text-success">Успешно добавлено</span>',
                'footer'=> Html::button('Ок',['class'=>'btn btn otmena pull-left','data-dismiss'=>"modal"]).
                        Html::a('Создать ещё',['/tasks/add_rab', 'client_id' => $client_id],['class'=>'btn btn save','role'=>'modal-remote'])        
            ];         
        }else{           
            return [ 
                'title'=> "Добавить. Задачи",
                'size' => 'large',
                'content'=>$this->renderAjax('/tasks/add_rab', [
                    'model' => $model,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn otmena pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn save','type'=>"submit"])        
            ];         
        }     
    }
    /**
     * Updates an existing Tasks model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdateTasks($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);       

        Yii::$app->response->format = Response::FORMAT_JSON;
        if($model->load($request->post()) && $model->save()){
            return ['forceClose'=>true,'forceReload'=>'#tasks-datatable-pjax'];
        }else{
             return [
                'title'=> "Изменить",
                'size' => 'large',
                'content'=>$this->renderAjax('/tasks/update', [
                    'model' => $model,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn otmena pull-left','data-dismiss'=>"modal"]).
                            Html::button('Сохранить',['class'=>'btn btn save','type'=>"submit"])
            ];        
        }
    }
    /**
     * Delete an existing Tasks model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDeleteTasks($id)
    {
        $request = Yii::$app->request;
        $model = Tasks::findOne($id);
        $imageName = $model->attachment;
        Yii::$app->db->createCommand()->delete('tasks', ['id' => $id])->execute();
        unlink(getcwd().'/uploads/'.$imageName);

       // $this->findModel($id)->delete();

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#tasks-datatable-pjax'];
        }
    }
    /**
     * Creates a new Tasks model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Tasks();  
        if(Yii::$app->user->identity->type != 1) $model->who_users_id = Yii::$app->user->identity->id; 

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($model->load($request->post()) && $model->validate()){

                $model->other_file = UploadedFile::getInstance($model, 'other_file');
                $imageName = $model->other_file->baseName . '.' . $model->other_file->extension;

                if (!empty($model->other_file)) {
                    $model->attachment = $imageName;
                    $model->other_file->saveAs('uploads/' . $imageName);
                }

                $model->save();

views/tasks/_columns.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use app\models\Users;
use yii\helpers\ArrayHelper;
use dosamigos\datepicker\DatePicker;
use kartik\time\TimePicker;

return [
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'title',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'date',
        'filter' => DatePicker::widget([
            'model' => $searchModel,
            'attribute' => 'date',
            'language' => 'ru',
                'clientOptions' => [
            'language' => 'ru',
                    'autoclose' => true,
                    'format' => 'yyyy-mm-dd'
                ]
        ]),
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'time',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'who_users_id',
        'filter' => ArrayHelper::map(Users::find()->all(),'id','fio'),
        'content' => function($data){
            return $data->whoUsers->fio;
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'to_users_id',
        'filter' => ArrayHelper::map(Users::find()->all(),'id','fio'),
        'content' => function($data){
            return $data->toUsers->fio;
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'status',
        'filter'=>array("1"=>"Выполнено","2"=>"На проверке","3"=>"Есть уточнение","4"=>"Новая"),
        'content' => function($data){
            return $data->getStatusName();
        }
    ],
    [
        'class'    => 'kartik\grid\ActionColumn',
        'template' => ' {view} {update} {leadDelete}',
        'viewOptions'=>['role'=>'modal-remote','title'=>'','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'', 'data-toggle'=>'tooltip'],
        'buttons'  => [
            'leadDelete' => function ($url, $model) {
                if(Yii::$app->user->identity->type == 1){
                    $url = Url::to(['/tasks/delete', 'id' => $model->id]);
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                        'role'=>'modal-remote','title'=>'', 
                              'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                              'data-request-method'=>'post',
                              'data-toggle'=>'tooltip',
                              'data-confirm-title'=>'Подтвердите действие',
                              'data-confirm-message'=>'Вы уверены что хотите удалить этот элемент?',
                    ]);
                }
            },
        ]
    ]

];   

views/tasks/_create_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use kartik\time\TimePicker;
/* @var $this yii\web\View */
/* @var $model app\models\Tasks */
/* @var $form yii\widgets\ActiveForm */
$user_id = Yii::$app->user->identity->id;
$disabled = false;
if(!$model->isNewRecord && $model->to_users_id == $user_id && Yii::$app->user->identity->type != 1) $disabled = true;
?>

<div class="tasks-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <img style="width: 100%;margin-top: -60px" src="/theme/assets/img/chiziq95.png" alt="">
        <div class="col-md-3 label1">
            <?=$model->getAttributeLabel('client_id')?>
        </div>
        <div class="col-md-5" style="margin-left: -75px;">
            <?= $form->field($model, 'client_id')->label()->widget(\kartik\select2\Select2::classname(), [
                'data' => $model->getClients(),
                'disabled' => $disabled,
                'options' => ['placeholder' => 'Выберите'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 label1" style="margin-top: 0px">
            <?=$model->getAttributeLabel('title')?>
        </div>
        <div class="col-md-5" style="margin-left: -75px;margin-top: -20px">
            <?= $form->field($model, 'title')->textInput(['maxlength' => true, 'disabled' => $disabled])->label(""); ?>           
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 label1" style="margin-top: 0px">
            <?=$model->getAttributeLabel('who_users_id')?>
        </div>
        <div class="col-md-5" style="margin-left: -75px;margin-top: -20px">
            <?= $form->field($model, 'who_users_id')->dropDownList($model->getUsers(), ['prompt' => 'Выберите',  'disabled' => $disabled ? true : (Yii::$app->user->identity->type == 1 ? false : true) ])->label(""); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 label1" style="margin-top: 0px">
            <?=$model->getAttributeLabel('to_users_id')?>
        </div>
        <div class="col-md-5" style="margin-left: -75px;margin-top: -20px">
            <?= $form->field($model, 'to_users_id')->dropDownList($model->getUsers(), ['prompt' => 'Выберите', 'disabled' => $disabled ])->label(""); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 label1" style="margin-top: 0px">
            <?=$model->getAttributeLabel('terms')?>
        </div>
        <div class="col-md-5" style="margin-left: -75px;margin-top: -20px">
            <?= $form->field($model, 'terms')->widget(DatePicker::classname(), [
                'options' => ['placeholder' => 'Выберите дату',],
                'removeButton' => false,
                'disabled' => $disabled,
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd',
                ]
            ])->label("");
            ?>
        </div>  
        <div class="col-md-4" style="margin-top: -192px;margin-left: 60px;">
            <?= $form->field($model, 'description')->textarea(['rows' => 14]); ?>
        </div>      
    </div>
    <div class="row">
       <div class="col-md-2 label1" style="margin-top: 35px;">
            <?=$model->getAttributeLabel('other_file')?>
        </div>
        <div class="col-md-3" style="margin-top: 21px;"> 
            <?= $form->field($model, 'other_file')->fileInput()->label("") ?>        
        </div>
    </div>
    <div style="display: none;">
        <?= $form->field($model, 'status')->textInput(['value' => 4]) ?>        
    </div>
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/tasks/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use kartik\time\TimePicker;
/* @var $this yii\web\View */
/* @var $model app\models\Tasks */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tasks-form">
 
    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <img style="width: 100%;margin-top: -60px" src="/theme/assets/img/chiziq95.png" alt="">
         <div class="col-md-6">
            <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>           
        </div>
       
        <div class="col-md-6">
            <?= $form->field($model, 'status')->dropDownList($model->getStatus(), ['prompt' => 'Выберите', 'id' => 'type']) ?>          
        </div>
      
    </div> 
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'who_users_id')->dropDownList($model->getUsers(), ['prompt' => 'Выберите', 'id' => 'type']) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'to_users_id')->dropDownList($model->getUsers(), ['prompt' => 'Выберите', 'id' => 'type']) ?>
        </div>
         <div class="col-md-4">
            <?= $form->field($model, 'terms')->widget(DatePicker::classname(), [
                'options' => ['placeholder' => 'Выберите дату',],
                'removeButton' => false,
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd',
                ]
            ]);
            ?>
        </div>
       
        
    </div>
    <div class="row">
       
        <div class="col-md-12">
            <?= $form->field($model, 'description')->textarea(['rows' => 4]) ?>          
        </div>
    </div>
    <div class="row">
        <div class="col-md-3"> 
            <?= $form->field($model, 'other_file')->fileInput() ?>        
        </div>
    </div>
    <div style="display: none;">
        <?= $form->field($model, 'client_id')->textInput() ?>
    </div>
  
    <?php if (!Yii::$app->request->isAjax){ ?>
        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    <?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/tasks/add.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\tasks */

?>
<div class="tasks-create">
    <?= $this->render('add_form', [
        'model' => $model,
    ]) ?>
</div>

views/tasks/add_rab.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\tasks */

?>
<div class="tasks-create">
    <?= $this->render('add_rab_form', [
        'model' => $model,
    ]) ?>
</div>

views/tasks/chat.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use rmrevin\yii\module\Comments;

$this->title = "Чат";
$this->params['breadcrumbs'][] = $this->title;


?>
<head>
    <link href="/theme/assets/css/new.css" rel="stylesheet" />
</head>
<body >
<div class="panel panel-inverse users-index">
    <div class="panel-heading" style="background: #28292b">
        <h4 class="panel-title rabsize3 left1">Чат</h4>
        <span class="pull-right"><?= Html::a('Назад', ['/tasks/index'],
                    ['data-pjax'=>'0','title'=> 'Назад','class'=>'btn btn-warning btn-xs', 'style' => 'margin-top:-35px;' ])?></span>
    </div>
    <div class="panel-body">
        <?php echo Comments\widgets\CommentListWidget::widget(['entity' => 'tasks' ]);?>
    </div>
</div>
</body>

views/tasks/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Tasks */

?>
<div class="tasks-create">
    <?= $this->render('_create_form', [
        'model' => $model,
    ]) ?>
</div>

views/tasks/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UsersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = "Задачи";
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<head>
    <link href="/theme/assets/css/new.css" rel="stylesheet" />
</head>
<body >
<div class="panel panel-inverse users-index leftindexclient">
    <div class="panel-heading" style="background: #28292b">
        <h4 class="panel-title rabsize3 left1" >Задачи</h4>
        <span class="pull-right">
            <?= $status==1 ? Html::a('Актив', ['/tasks/index'],
                    ['title'=> '','style'=>'color: #ffffff;background:#74b916;margin-top: -35px','class'=>'btn btn-xs'])
                    : Html::a('Архив', ['/tasks/archive'],
                    ['title'=> '','style'=>'color: #ffffff;background:#74b916;margin-top: -35px','class'=>'btn btn-xs'])
            ?>
        </span>
    </div>
    <div class="panel-body">
        <div id="ajaxCrudDatatable">
            <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'pjax'=>true,
            'columns' => require(__DIR__.'/_columns.php'),
            'panelBeforeTemplate' =>    Html::a('Добавить <i  class="fa fa"></i>', ['create'],
                    ['role'=>'modal-remote','title'=> 'Добавить','style'=>'color: #ffffff;background:#74b916;margin-left: 25px','class'=>'btn btn']).'&nbsp;'.
                Html::a('Чат', ['/tasks/chat'],
                    ['data-pjax'=>'0','title'=> 'Чат','style'=>'margin-left: 12px','class'=>'btn btn-warning']).'&nbsp;'.
                Html::a('<i class="fa fa-repeat"></i>', [''],
                    ['data-pjax'=>1,'style'=>'color: #ffffff;background:#74b916;margin-left: 12px', 'class'=>'btn btn', 'title'=>'Обновить']),
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'panel' => [
            'headingOptions' => ['style' => 'display: none;'],
            'after'=>'',
            ]
            ])?>
        </div>
    </div>
</div>
</body>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "options" => [
        "tabindex" => -1,
    ],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/tasks/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Tasks */
?>
<div class="tasks-update">

    <?= $this->render('_update', [
        'model' => $model,
    ]) ?>

</div>

views/tasks/view.php
<?php

use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Tasks */
?>
<div class="tasks-view">
 
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            [
                'attribute' => 'client_id',
                'value' => function ($data) {
                  return $data->client->working_title;
                },
            ],
            'title',
            [
                    'attribute' => 'date',
                    'value' => function ($data) {
                     if($data->date != null )  return \Yii::$app->formatter->asDate($data->date, 'php:d.m.Y');
                    },
            ],
            [
                'attribute' => 'who_users_id',
                'value' => function ($data) {
                  return $data->whoUsers->fio;
                },
            ],
            [
                'attribute' => 'to_users_id',
                'value' => function ($data) {
                  return $data->toUsers->fio;
                },
            ],
            [
                'attribute' => 'status',
                'format' => 'raw',
                'value' => function ($data) {
                    return \yii\helpers\ArrayHelper::map([
                        ['id' => 1,
                            'title' => 'Выполнено',],
                        ['id' => 2,
                            'title' => 'На проверке',],
                        ['id' => 3,
                            'title' => 'Есть уточнение',],
                        ['id' => 4,
                            'title' => 'Новая',],
                    ], 'id', 'title')[$data->status];
                }
              ],
            [
            'attribute'=>'description',
            'format'=>'ntext',   
            'contentOptions' => [
                'style'=>'max-width:150px; min-height:100px; overflow: auto; word-wrap: break-word;'
            ],
            ],
            'terms',
            ],
    ]) ?>

</div>